# Site settings
title: Hello Ayo
email: hireayo@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  The portfolio site of Ayo Suber.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://helloayo.com" # the base hostname & protocol for your site
twitter_username: helloayo
github_username:  helloayo

# Build settings
markdown: kramdown
gems:
  - jekyll-angular